plugins:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
        - "java-design"
        - "java-android"	
  sonar-java:
    enabled: true
    config:
      minimum_severity: info
      
